import Head from 'next/head'
import { Fragment, useEffect, useState } from 'react';

import { useRouter } from 'next/router'

import { Loader } from 'rsuite';

import { GETData } from '../services/WebServices'

import Product from "../components/Product";
import Chat from "../components/Chat";

export default function Catalog() {

  const router = useRouter();

  const [products, setProducts] = useState([]);

  useEffect(() => {
    GETData("/api/products", "GET")
      .then(response => setProducts(response))
  },[]);

  return (
    <Fragment>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{router.query.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/store.ico" />
      </Head>
       
        {products.length ?
        <div className="w-100 vh-100 bg-white column-start align-items-start p-4 position-relative">
            <div className="txt-dark-blue txt-28 txt-bold mb-5">{router.query.name}</div>
            <div className="row-start align-items-center flex-wrap">
                {products.map(product => <Product key={product._ref} {...product}/>)}
            </div>
            <Chat name={router.query.name} number={router.query.number_contact}/>
        </div> :
        <div className="w-100 h-100 bg-white row-center align-items-center">
            <Loader center size="md" content="Cargando..." />
        </div>}
    </Fragment>
  )
}