import Head from 'next/head'
import { Fragment, useEffect, useState } from 'react';

import { GETData } from '../services/WebServices'

import Brand from "../components/Brand";

export default function Main() {

  const [brands, setBrands] = useState([]);

  useEffect(() => {
    GETData("/api/brands", "GET")
      .then(response => setBrands(response))
  },[]);

  return (
    <Fragment>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Mall virtual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/store.ico" />
      </Head>
      
      <div className="w-100 vh-100 bg-white row-center align-items-center">
        {
          brands.length ?
            brands.map(brand => <Brand key={brand.id} {...brand}/>) : null
        }
      </div>
    </Fragment>
  )
}
