import Head from 'next/head'
import { connect } from 'react-redux';
import { Fragment, useEffect } from 'react';

import * as sharedActions from '../store/shared/Actions'

import { Loader } from 'rsuite';

import Brand from "../components/Brand";

function Main(props) {

  useEffect(() => props.loadBrandsAsync(),[]);

  return (
    <Fragment>
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Mall virtual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/store.ico" />
      </Head>
      
      {props.brands.length ?
      <div className="vh-100 w-100">
        <div className="h-100 bg-white column-center align-items-center p-3">
          <div className="row-center align-items-center">
            <div className="txt-dark-blue txt-28 txt-bold text-center text-wrap">Bienvenido a nuestra tienda virtual</div>
          </div>
          <div className="row-center align-items-center flex-wrap">
            {props.brands.map(brand => <Brand key={brand.id} {...brand}/>)}
          </div>
        </div>
      </div> :
      <div className="w-100 h-100 bg-white row-center align-items-center">
        <Loader center size="md" content="Cargando..." />
      </div>}
    </Fragment>
  )
}

const mapStateToProps = (state) => ({
  brands: state.shared.brands
})

const mapDispatchToProps = dispatch => ({
  loadBrandsAsync: () => dispatch(sharedActions.loadBrandsAsync())
})

export default connect(mapStateToProps, mapDispatchToProps)(Main)